--------------------------------------------------------
--  文件已创建 - 星期日-十月-14-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BLOG
--------------------------------------------------------

   CREATE SEQUENCE  "WSC_BLOG"."SEQ_BLOG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 103 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INDEX
--------------------------------------------------------

   CREATE SEQUENCE  "WSC_BLOG"."SEQ_INDEX"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTE
--------------------------------------------------------

   CREATE SEQUENCE  "WSC_BLOG"."SEQ_NOTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTICE
--------------------------------------------------------

   CREATE SEQUENCE  "WSC_BLOG"."SEQ_NOTICE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER
--------------------------------------------------------

   CREATE SEQUENCE  "WSC_BLOG"."SEQ_USER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1007 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BLOG_ADMIN
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_ADMIN" 
   (	"ADMIN_ID" NUMBER, 
	"ADMIN_NAME" VARCHAR2(20 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BLOG_ARTICLE
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_ARTICLE" 
   (	"BA_ID" NUMBER, 
	"BA_TITLE" VARCHAR2(200 BYTE), 
	"BA_CONTENT" CLOB, 
	"BA_TIME" DATE, 
	"USER_ID" NUMBER DEFAULT 1000, 
	"BA_STATUS" VARCHAR2(20 BYTE) DEFAULT '待审核'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BA_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BLOG_INDEX
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_INDEX" 
   (	"BI_ID" NUMBER, 
	"BA_ID" NUMBER, 
	"BI_TITLE" VARCHAR2(100 BYTE), 
	"BI_DESCRIBE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BLOG_NOTE
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_NOTE" 
   (	"NOTE_ID" NUMBER, 
	"NOTE_CONTENT" VARCHAR2(100 BYTE), 
	"NOTE_TIME" DATE, 
	"USER_ID" NUMBER, 
	"BA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BLOG_NOTICE
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_NOTICE" 
   (	"BN_ID" NUMBER, 
	"BN_TITLE" VARCHAR2(100 BYTE), 
	"BN_CONTENT" CLOB, 
	"BN_TIME" DATE, 
	"ADMIN_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("BN_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BLOG_SORT
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_SORT" 
   (	"BA_ID" NUMBER, 
	"BS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BLOG_SORT_INFO
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_SORT_INFO" 
   (	"BS_ID" NUMBER, 
	"BS_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BLOG_USER
--------------------------------------------------------

  CREATE TABLE "WSC_BLOG"."BLOG_USER" 
   (	"USER_ID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE, 
	"ICON" VARCHAR2(50 BYTE) DEFAULT '1.jpg', 
	"REAL_NAME" VARCHAR2(20 BYTE), 
	"SEX" VARCHAR2(20 BYTE), 
	"INSTITUTE" VARCHAR2(40 BYTE), 
	"BIRTHDAY" DATE, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CONTACT" VARCHAR2(50 BYTE), 
	"INTRODUCE" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View BLOG_USERINFO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "WSC_BLOG"."BLOG_USERINFO" ("USER_ID", "REAL_NAME", "SEX", "INSTITUTE", "BIRTHDAY", "EMAIL", "CONTACT", "INTRODUCE") AS 
  SELECT 
    user_id,real_name,sex,institute,birthday,email,contact,introduce
FROM 
    blog_user;
REM INSERTING into WSC_BLOG.BLOG_ADMIN
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_ADMIN (ADMIN_ID,ADMIN_NAME,ADMIN_PASSWORD) values (1,'admin','admin');
Insert into WSC_BLOG.BLOG_ADMIN (ADMIN_ID,ADMIN_NAME,ADMIN_PASSWORD) values (2,'admin1','admin');
REM INSERTING into WSC_BLOG.BLOG_ARTICLE
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (4,'人生比港剧更传奇的TVB最佳女主角逝去了',to_date('24-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (1,'这是第一条',to_date('21-11月-17','DD-MON-RR'),1000,'不通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (2,'摔倒的奚梦瑶、站着看秀的王思聪、爆炸头的张靓颖，谁能为30万门票的维密秀挽尊？',to_date('21-11月-17','DD-MON-RR'),1000,'不通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (3,'如何看待某直播平台未成年女性晒怀孕视频',to_date('21-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (5,'女明星的豪门梦：困于修罗场中与命运抗争',to_date('24-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (6,'陈羽凡凭什么不能让白百何事件“翻篇儿”',to_date('24-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (7,'联盟顶级3D球员，是怎样炼成的？',to_date('24-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (8,'伊斯坦布尔的债，要还到啥时候？',to_date('24-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (9,'其实，恩比德和西蒙斯，加起来有60多岁了',to_date('24-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (10,'双城记：上海虹桥与北京南的爱与恨',to_date('26-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (11,'万篇黑稿攻击阿里背后：方兴东被曝与京东签200万合同打击天猫',to_date('26-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (12,'罗维尼：不止有亚德里亚海上最美的夕阳',to_date('28-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (13,'三里屯美女街拍：每个女人都该掌握的穿搭技巧 ',to_date('28-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (14,'五月，冰城紫色浪漫的最美时光',to_date('28-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (15,'【黄芽菜炒年糕】上海人常吃的年糕 ',to_date('28-11月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (26,'使用一个过滤器Filter同时过滤多个资源',to_date('04-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (28,'Tiffany曲别针卖一万三，是不是以为我们“洒”？',to_date('04-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (27,'沈嘉柯评《寻梦环游记》：如果你活着，请别忘了我 ',to_date('04-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (29,'#有机触手可及#【无水蒸鸡】滴水不加做鲜美蒸鸡',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (30,'笑die! 71岁的侯耀华收了个3国混血妖艳女徒弟，还辣眼睛的狂秀恩爱了',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (31,'旁听江歌案：刘鑫疑似撒谎，嫌犯毫无悔意，江妈妈埋头痛哭',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (32,'关于南京大屠杀，日本的历史教育回避了什么？',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (33,'为什么有的人总也存不住钱？',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (34,'张盛舒：2018年要特别当心感情出问题的5大紫微命格',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (35,'好斗的周鸿祎挥起黑公关大棒，敌人却是空气 ',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (36,'小朋友的很多问题是大人一手造成的',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (37,'【场合着装】《欢乐颂》里的五美你爱谁？轻熟OL究竟应该如何穿？',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (38,'窦靖童出家？这件事和90后丧掉都不是真的',to_date('14-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (61,'中领馆：泰国大象骑行等项目存风险，游客需谨慎',to_date('27-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (62,'艾滋病暴露前预防，为什么难以推广？',to_date('27-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (63,'《红楼梦》教给女人的10个道理，个个戳心！ ',to_date('27-12月-17','DD-MON-RR'),1000,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (64,'什么样的美，吸引着这么多游人来雪乡呢？',to_date('27-12月-17','DD-MON-RR'),1002,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (65,'史上最繁华的宋朝为什么经常闹“钱荒”',to_date('27-12月-17','DD-MON-RR'),1002,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (66,'“佛系青年”的含义',to_date('27-12月-17','DD-MON-RR'),1002,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (67,'三问 “同一天出生的你”：善款到底是不是捐给同一天出生的TA',to_date('27-12月-17','DD-MON-RR'),1002,'通过');
Insert into WSC_BLOG.BLOG_ARTICLE (BA_ID,BA_TITLE,BA_TIME,USER_ID,BA_STATUS) values (101,'毕业设计“湖师空间”小记录',to_date('03-1月 -18','DD-MON-RR'),1000,'通过');
REM INSERTING into WSC_BLOG.BLOG_INDEX
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_INDEX (BI_ID,BA_ID,BI_TITLE,BI_DESCRIBE) values (11,38,'窦靖童出家？这件事和90后丧掉都不是真的','12日晚间的朋友圈，被一则窦靖童“剃度”的视频刷爆了结尾处还隐约露出羞涩笑容							
							');
Insert into WSC_BLOG.BLOG_INDEX (BI_ID,BA_ID,BI_TITLE,BI_DESCRIBE) values (12,35,'好斗的周鸿祎挥起黑公关大棒，敌人却是空气 ','最近，因为水滴直播的名誉问题，周鸿祎和一个92年女生怼起来了,周鸿祎挥舞的是一个叫做“黑公关”的大棒
							
							');
Insert into WSC_BLOG.BLOG_INDEX (BI_ID,BA_ID,BI_TITLE,BI_DESCRIBE) values (10,66,'“佛系青年”的含义','最近流行所谓“佛系青年”的议题，成为一个社会的热点和焦点							
							');
Insert into WSC_BLOG.BLOG_INDEX (BI_ID,BA_ID,BI_TITLE,BI_DESCRIBE) values (13,33,'为什么有的人总也存不住钱？','生活中总有人抱怨自己存不住钱，无论赚多少都难有积蓄，常常是手里的钱刚多了一些，自然就会有事让他不得不把多出来的钱花掉								
							');
Insert into WSC_BLOG.BLOG_INDEX (BI_ID,BA_ID,BI_TITLE,BI_DESCRIBE) values (14,32,'关于南京大屠杀，日本的历史教育回避了什么？','这两天对于许多中国人来说，是一个很沉重的日子。谈到二战，谈到南京大屠杀，尽管这些话题是中国人民心中一直过不去的坎儿								
							');
Insert into WSC_BLOG.BLOG_INDEX (BI_ID,BA_ID,BI_TITLE,BI_DESCRIBE) values (16,101,'毕业设计“湖师空间”小记录','做完毕业设计非常不容易，真的不容易，不容易啊不容易							
							');
Insert into WSC_BLOG.BLOG_INDEX (BI_ID,BA_ID,BI_TITLE,BI_DESCRIBE) values (17,14,'五月，冰城紫色浪漫的最美时光','五月，丁香花开遍哈尔滨的大街小巷，五月，丁香花以城市的爱恋绽放芬芳，五月，是哈尔滨幽香飘洒的季节					
							');
REM INSERTING into WSC_BLOG.BLOG_NOTE
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (1,'嘻嘻嘻',to_date('31-12月-17','DD-MON-RR'),1000,38);
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (2,'2018!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!',to_date('01-1月 -18','DD-MON-RR'),1000,38);
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (3,'2018!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!',to_date('01-1月 -18','DD-MON-RR'),1000,38);
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (4,'2017!!!!!!!!!!!!!!!!!!!!!!!!!!!',to_date('01-1月 -18','DD-MON-RR'),1000,38);
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (5,'lala',to_date('01-1月 -18','DD-MON-RR'),1000,38);
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (6,'你好！！！',to_date('01-1月 -18','DD-MON-RR'),1000,38);
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (15,'南京大屠杀！！',to_date('03-1月 -18','DD-MON-RR'),0,32);
Insert into WSC_BLOG.BLOG_NOTE (NOTE_ID,NOTE_CONTENT,NOTE_TIME,USER_ID,BA_ID) values (18,'wwww',to_date('25-4月 -18','DD-MON-RR'),1000,102);
REM INSERTING into WSC_BLOG.BLOG_NOTICE
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_NOTICE (BN_ID,BN_TITLE,BN_TIME,ADMIN_ID) values (1,'“远航2018”国外留学项目(五) --中美1+2+1双学位项目',to_date('12-12月-17','DD-MON-RR'),1);
Insert into WSC_BLOG.BLOG_NOTICE (BN_ID,BN_TITLE,BN_TIME,ADMIN_ID) values (2,'如何办理因私护照',to_date('12-12月-17','DD-MON-RR'),1);
Insert into WSC_BLOG.BLOG_NOTICE (BN_ID,BN_TITLE,BN_TIME,ADMIN_ID) values (19,'信息工程学院举行毕业答辩',to_date('03-1月 -18','DD-MON-RR'),1);
Insert into WSC_BLOG.BLOG_NOTICE (BN_ID,BN_TITLE,BN_TIME,ADMIN_ID) values (20,'系统正在不断升级中',to_date('03-1月 -18','DD-MON-RR'),1);
Insert into WSC_BLOG.BLOG_NOTICE (BN_ID,BN_TITLE,BN_TIME,ADMIN_ID) values (21,'哈哈哈',to_date('03-1月 -18','DD-MON-RR'),1);
Insert into WSC_BLOG.BLOG_NOTICE (BN_ID,BN_TITLE,BN_TIME,ADMIN_ID) values (17,'著名作曲家陈钢做客胡瑗大讲堂 ',to_date('14-12月-17','DD-MON-RR'),1);
Insert into WSC_BLOG.BLOG_NOTICE (BN_ID,BN_TITLE,BN_TIME,ADMIN_ID) values (18,'湖州师范学院厉害了',to_date('03-1月 -18','DD-MON-RR'),1);
REM INSERTING into WSC_BLOG.BLOG_SORT
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (3,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (4,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (28,1);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (5,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (6,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (14,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (27,4);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (7,4);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (10,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (8,4);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (9,4);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (11,1);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (12,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (13,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (15,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (26,5);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (38,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (29,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (30,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (31,1);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (32,1);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (33,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (34,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (67,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (66,1);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (35,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (101,5);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (36,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (37,2);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (61,1);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (62,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (63,5);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (64,3);
Insert into WSC_BLOG.BLOG_SORT (BA_ID,BS_ID) values (65,5);
REM INSERTING into WSC_BLOG.BLOG_SORT_INFO
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_SORT_INFO (BS_ID,BS_NAME) values (0,'校园类');
Insert into WSC_BLOG.BLOG_SORT_INFO (BS_ID,BS_NAME) values (1,'时事类');
Insert into WSC_BLOG.BLOG_SORT_INFO (BS_ID,BS_NAME) values (2,'娱乐类');
Insert into WSC_BLOG.BLOG_SORT_INFO (BS_ID,BS_NAME) values (3,'生活类');
Insert into WSC_BLOG.BLOG_SORT_INFO (BS_ID,BS_NAME) values (4,'体育类');
Insert into WSC_BLOG.BLOG_SORT_INFO (BS_ID,BS_NAME) values (5,'学术类');
Insert into WSC_BLOG.BLOG_SORT_INFO (BS_ID,BS_NAME) values (6,'其他类');
REM INSERTING into WSC_BLOG.BLOG_USER
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1000,'wsc','wsc123',null,'1.jpg',null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1001,'wss','wss123',null,'1.jpg',null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1002,'wsc1','wsc123',null,'1.jpg',null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1003,'wsc2','wsc123',null,'1.jpg',null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1004,'wsc3','wsc123',to_date('29-12月-17','DD-MON-RR'),'1.jpg',null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (0,'未知用户','000000',null,'1.jpg',null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1005,'wsc4','wsc123',to_date('29-12月-17','DD-MON-RR'),'1.jpg',null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USER (USER_ID,USERNAME,PASSWORD,REG_DATE,ICON,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1006,'wsc5','wsc123',to_date('02-1月 -18','DD-MON-RR'),'1.jpg',null,null,null,null,null,null,null);
REM INSERTING into WSC_BLOG.BLOG_USERINFO
SET DEFINE OFF;
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1000,null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1001,null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1002,null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1003,null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1004,null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (0,null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1005,null,null,null,null,null,null,null);
Insert into WSC_BLOG.BLOG_USERINFO (USER_ID,REAL_NAME,SEX,INSTITUTE,BIRTHDAY,EMAIL,CONTACT,INTRODUCE) values (1006,null,null,null,null,null,null,null);
--------------------------------------------------------
--  DDL for Index BLOG_ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WSC_BLOG"."BLOG_ADMIN_PK" ON "WSC_BLOG"."BLOG_ADMIN" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BLOG_ARTICLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WSC_BLOG"."BLOG_ARTICLE_PK" ON "WSC_BLOG"."BLOG_ARTICLE" ("BA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BLOG_INDEX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WSC_BLOG"."BLOG_INDEX_PK" ON "WSC_BLOG"."BLOG_INDEX" ("BI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BLOG_NOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WSC_BLOG"."BLOG_NOTE_PK" ON "WSC_BLOG"."BLOG_NOTE" ("NOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BLOG_NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WSC_BLOG"."BLOG_NOTICE_PK" ON "WSC_BLOG"."BLOG_NOTICE" ("BN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BLOG_SORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WSC_BLOG"."BLOG_SORT_PK" ON "WSC_BLOG"."BLOG_SORT" ("BA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007193
--------------------------------------------------------

  CREATE UNIQUE INDEX "WSC_BLOG"."SYS_C007193" ON "WSC_BLOG"."BLOG_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BLOG_ADMIN
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_ADMIN" ADD CONSTRAINT "BLOG_ADMIN_PK" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WSC_BLOG"."BLOG_ADMIN" MODIFY ("ADMIN_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_ADMIN" MODIFY ("ADMIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG_ARTICLE
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_ARTICLE" MODIFY ("BA_STATUS" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_ARTICLE" ADD CONSTRAINT "BLOG_ARTICLE_PK" PRIMARY KEY ("BA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WSC_BLOG"."BLOG_ARTICLE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_ARTICLE" MODIFY ("BA_TIME" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_ARTICLE" MODIFY ("BA_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_ARTICLE" MODIFY ("BA_TITLE" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_ARTICLE" MODIFY ("BA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG_INDEX
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_INDEX" ADD CONSTRAINT "BLOG_INDEX_PK" PRIMARY KEY ("BI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WSC_BLOG"."BLOG_INDEX" MODIFY ("BI_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG_NOTE
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_NOTE" ADD CONSTRAINT "BLOG_NOTE_PK" PRIMARY KEY ("NOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WSC_BLOG"."BLOG_NOTE" MODIFY ("BA_ID" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTE" MODIFY ("NOTE_TIME" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTE" MODIFY ("NOTE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTE" MODIFY ("NOTE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG_NOTICE
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_NOTICE" ADD CONSTRAINT "BLOG_NOTICE_PK" PRIMARY KEY ("BN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WSC_BLOG"."BLOG_NOTICE" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTICE" MODIFY ("BN_TIME" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTICE" MODIFY ("BN_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTICE" MODIFY ("BN_TITLE" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_NOTICE" MODIFY ("BN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG_SORT
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_SORT" ADD CONSTRAINT "BLOG_SORT_PK" PRIMARY KEY ("BA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WSC_BLOG"."BLOG_SORT" MODIFY ("BS_ID" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_SORT" MODIFY ("BA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG_SORT_INFO
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_SORT_INFO" MODIFY ("BS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG_USER
--------------------------------------------------------

  ALTER TABLE "WSC_BLOG"."BLOG_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WSC_BLOG"."BLOG_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "WSC_BLOG"."BLOG_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
